<a href="https://colab.research.google.com/github/SAIKUMAR500/ANN-classification/blob/main/ANN_Classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.metrics import confusion_matrix, classification_report
from keras.models import Sequential
from keras.layers import Dense

In [ ]:
df = pd.read_csv('/content/Churn_Modelling (AI).csv')

In [ ]:
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  object
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  object
 5   Gender           10000 non-null  object
 6   Age              10000 non-null  int64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB

In [ ]:
df.columns

Index(['RowNumber', 'CustomerId', 'Surname', 'CreditScore', 'Geography',
       'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Exited'],
      dtype='object')

In [ ]:
df.describe()

,RowNumber,CustomerId,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
count,10000.00000,1.000000e+04,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000
mean,5000.50000,1.569094e+07,650.528800,38.921800,5.012800,76485.889288,1.530200,0.70550,0.515100,100090.239881,0.203700
std,2886.89568,7.193619e+04,96.653299,10.487806,2.892174,62397.405202,0.581654,0.45584,0.499797,57510.492818,0.402769
min,1.00000,1.556570e+07,350.000000,18.000000,0.000000,0.000000,1.000000,0.00000,0.000000,11.580000,0.000000
25%,2500.75000,1.562853e+07,584.000000,32.000000,3.000000,0.000000,1.000000,0.00000,0.000000,51002.110000,0.000000
50%,5000.50000,1.569074e+07,652.000000,37.000000,5.000000,97198.540000,1.000000,1.00000,1.000000,100193.915000,0.000000
75%,7500.25000,1.575323e+07,718.000000,44.000000,7.000000,127644.240000,2.000000,1.00000,1.000000,149388.247500,0.000000
max,10000.00000,1.581569e+07,850.000000,92.000000,10.000000,250898.090000,4.000000,1.00000,1.000000,199992.480000,1.000000

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns
df[ 'CreditScore'].value_counts()

850    233
678     63
655     54
705     53
667     53
      ...
404      1
351      1
365      1
417      1
419      1
Name: CreditScore, Length: 460, dtype: int64

In [ ]:
# Remove null values
df = df.dropna()

# Drop unnecessary columns
df = df.drop(['RowNumber', 'CustomerId', 'Surname'], axis=1)

# Label Encoding for categorical columns
label_encoder = LabelEncoder()
df['Geography'] = label_encoder.fit_transform(df['Geography'])
df['Gender'] = label_encoder.fit_transform(df['Gender'])

print(df.head())

   CreditScore  Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619          0       0   42       2       0.00              1
1          608          2       0   41       1   83807.86              1
2          502          0       0   42       8  159660.80              3
3          699          0       0   39       1       0.00              2
4          850          2       0   43       2  125510.82              1

   HasCrCard  IsActiveMember  EstimatedSalary  Exited
0          1               1        101348.88       1
1          0               1        112542.58       0
2          1               0        113931.57       1
3          0               0         93826.63       0
4          1               1         79084.10       0

In [ ]:
# Handling duplicate records
df = df.drop_duplicates()

# Splitting into x (independent variables) and y (dependent variable)
x = df.drop('Exited', axis=1)
y = df['Exited']

# Standardize the data
scaler = StandardScaler()
x = scaler.fit_transform(x)

In [ ]:
print("x (Independent Variables):")
print(x[:5])  # Displaying the first 5 rows
print("\ny (Dependent Variable):")
print(y[:5])  # Displaying the first 5 rows

x (Independent Variables):
[[-0.32622142 -0.90188624 -1.09598752  0.29351742 -1.04175968 -1.22584767
  -0.91158349  0.64609167  0.97024255  0.02188649]
 [-0.44003595  1.51506738 -1.09598752  0.19816383 -1.38753759  0.11735002
  -0.91158349 -1.54776799  0.97024255  0.21653375]
 [-1.53679418 -0.90188624 -1.09598752  0.29351742  1.03290776  1.33305335
   2.52705662  0.64609167 -1.03067011  0.2406869 ]
 [ 0.50152063 -0.90188624 -1.09598752  0.00745665 -1.38753759 -1.22584767
   0.80773656 -1.54776799 -1.03067011 -0.10891792]
 [ 2.06388377  1.51506738 -1.09598752  0.38887101 -1.04175968  0.7857279
  -0.91158349  0.64609167  0.97024255 -0.36527578]]

y (Dependent Variable):
0    1
1    0
2    1
3    0
4    0
Name: Exited, dtype: int64

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

print("Training set shape:", x_train.shape, y_train.shape)
print("Test set shape:", x_test.shape, y_test.shape)

Training set shape: (8000, 10) (8000,)
Test set shape: (2000, 10) (2000,)

In [ ]:
# Step 5: Build and Train the ANN Model
model = Sequential()
model.add(Dense(units=8, activation='relu', input_dim=10))  # Adjust input_dim to 10
model.add(Dense(units=8, activation='relu'))
model.add(Dense(units=1, activation='sigmoid'))

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

model.fit(x_train, y_train, epochs=10, batch_size=32, validation_split=0.2)

Epoch 1/10
200/200 [==============================] - 2s 2ms/step - loss: 0.5874 - accuracy: 0.7394 - val_loss: 0.5163 - val_accuracy: 0.7987
Epoch 2/10
200/200 [==============================] - 0s 1ms/step - loss: 0.4980 - accuracy: 0.7934 - val_loss: 0.4717 - val_accuracy: 0.7987
Epoch 3/10
200/200 [==============================] - 0s 1ms/step - loss: 0.4668 - accuracy: 0.7934 - val_loss: 0.4481 - val_accuracy: 0.7987
Epoch 4/10
200/200 [==============================] - 0s 1ms/step - loss: 0.4504 - accuracy: 0.7930 - val_loss: 0.4372 - val_accuracy: 0.7987
Epoch 5/10
200/200 [==============================] - 0s 1ms/step - loss: 0.4397 - accuracy: 0.7959 - val_loss: 0.4282 - val_accuracy: 0.8075
Epoch 6/10
200/200 [==============================] - 0s 1ms/step - loss: 0.4285 - accuracy: 0.8100 - val_loss: 0.4169 - val_accuracy: 0.8206
Epoch 7/10
200/200 [==============================] - 0s 1ms/step - loss: 0.4137 - accuracy: 0.8244 - val_loss: 0.4039 - val_accuracy: 0.8363
Epoch 8/10
200/200 [==============================] - 0s 1ms/step - loss: 0.3990 - accuracy: 0.8386 - val_loss: 0.3929 - val_accuracy: 0.8363
Epoch 9/10
200/200 [==============================] - 0s 1ms/step - loss: 0.3877 - accuracy: 0.8447 - val_loss: 0.3846 - val_accuracy: 0.8444
Epoch 10/10
200/200 [==============================] - 0s 2ms/step - loss: 0.3792 - accuracy: 0.8498 - val_loss: 0.3776 - val_accuracy: 0.8494

In [ ]:
y_pred = model.predict(x_test)
y_pred = (y_pred > 0.5)

print(y_pred)

63/63 [==============================] - 0s 2ms/step
[[False]
 [False]
 [False]
 ...
 [False]
 [False]
 [False]]

In [ ]:
conf_matrix = confusion_matrix(y_test, y_pred)
class_report = classification_report(y_test, y_pred)
print("Confusion Matrix:\n", conf_matrix)
print("\nClassification Report:\n", class_report)

Confusion Matrix:
 [[1561   46]
 [ 245  148]]

Classification Report:
               precision    recall  f1-score   support

           0       0.86      0.97      0.91      1607
           1       0.76      0.38      0.50       393

    accuracy                           0.85      2000
   macro avg       0.81      0.67      0.71      2000
weighted avg       0.84      0.85      0.83      2000

In [ ]:
_, accuracy = model.evaluate(x_test, y_test)
print(f"\nStep 8: Report the ANN Model Accuracy\nANN Model Accuracy: {accuracy * 100:.2f}%")

63/63 [==============================] - 0s 930us/step - loss: 0.3659 - accuracy: 0.8545

Step 8: Report the ANN Model Accuracy
ANN Model Accuracy: 85.45%